### ISSUE TITLE
Tunesss

### ISSUE THREAD

**Issue by hidder** [pkruithof/Hidde-Says#2]
- [x] Raarrrrr https://www.youtube.com/watch?v=ek3jGqZkOZg
- [ ] Oh yes oh yes!! Ome kareltje in het huizzzzz!!!
- [ ] Ivo lach uit 'goed gelukt'
- [x] Ik denk het niet Job! Muwahahaha https://www.youtube.com/watch?v=nvhNHZdTf40

**Comment by marijnsinke** [comment]
http://www.dumpert.nl/mediabase/6657324/ee57908d/dikke_gerard_verrassen.html    Obese meneer aaaaaaaaaahh godver

http://www.dumpert.nl/mediabase/6647662/039b4a1b/mooie_versiertruc_.html   Zin in een gast vanavond. Ik ben er aaaaallll!

https://www.youtube.com/watch?v=Akl9k1OgibA   Gefeliciteerd he!!!

**Comment by marijnsinke** [comment]
Bob de huisbaas  http://www.bobdehuisbaas.nl/   Je hebt nooit geen geld. Van m'n zakken uitblijven. 5 euro's? Op je muil gauw. Je hebt altijd een grote muil gehad. Optieffuhhhh gauw!

**Comment by pkruithof** [comment]
* [ ] Ha GAAAYY!

**Comment by pkruithof** [comment]
Gerard Ekdom sounds: http://www.3fm.nl/mobiel/soundboard

**Comment by pkruithof** [comment]
How bout no: https://www.youtube.com/watch?v=71yoRDE6XNQ

**Comment by pkruithof** [comment]
Neeeeeeeerd! https://www.youtube.com/watch?v=Qud4fT_B3VI

**Comment by pkruithof** [comment]
Jon Bakker (he?): http://www.rufentuf.nl/johnbakker/
